#lang racket

(provide (all-defined-out))

(require "../data/defs.rkt")

(define 100-CONTINUE            (ws-status 100 "Continue"))
(define 200-OK                  (ws-status 200 "Ok"))
(define 201-CREATED             (ws-status 201 "Created"))
(define 202-ACCEPTED            (ws-status 202 "Accepted"))
(define 203-NON-AUTH            (ws-status 203 "Non-Authoratative Information"))
(define 204-NO-CONTENT          (ws-status 204 "No Contetn"))
(define 205-RESET-CONTENT       (ws-status 205 "Reset Content"))  
(define 206-PARTIAL-CONTENT     (ws-status 206 "Partial Content"))
(define 300-MULTIPLE-CHOICES    (ws-status 300 "Multiple Choices"))
(define 301-MOVED-PERM          (ws-status 301 "Moved Permanently"))
(define 302-FOUND               (ws-status 302 "Found"))
(define 303-SEE-OTHER           (ws-status 303 "See Other"))
(define 304-NOT-MODIFIED        (ws-status 304 "Not Modified"))
(define 307-TEMP-REDIRECT       (ws-status 307 "Temporary Redirect"))
(define 308-PERM-REDIRECT       (ws-status 308 "Permanent Redirect"))
(define 400-BAD-REQUEST         (ws-status 400 "Bad Request"))
(define 401-UNAUTHORIZED        (ws-status 401 "Unauthorized"))
(define 402-PAYMENT-REQUIRED    (ws-status 402 "Payment Required"))
(define 403-FORBIDDEN           (ws-status 403 "Forbidden"))
(define 404-NOT-FOUND           (ws-status 404 "Not Found"))
(define 405-METHOD-NOT-ALLOWED  (ws-status 405 "Method Not Allowed"))
(define 406-NOT-ACCEPTABLE      (ws-status 406 "Not Acceptable"))
(define 407-PROXY-AUTH-REQUIRED (ws-status 407 "Proxy Authentication Required"))
(define 408-TIMEOUT             (ws-status 408 "Request Timeout"))
(define 409-CONFLICT            (ws-status 409 "Conflict"))
(define 410-GONE                (ws-status 410 "Gone"))
(define 411-LENGTH-REQUIRED     (ws-status 411 "Length Required"))
(define 412-PRECOND-FAILED      (ws-status 412 "Precondition Failed"))
(define 413-ENTITY-TOO-LARGE    (ws-status 413 "Request Entity Too Large"))
(define 414-URI-TOO-LONG        (ws-status 414 "Request-URI Too Long"))
(define 415-UNSUPPORTED-MEDIA   (ws-status 415 "Unsupported Media Type"))
(define 416-RANGE-UNSAT         (ws-status 416 "Requested Range Not Satisfiable"))
(define 417-EXPECTATION-FAILED  (ws-status 417 "Expectation Failed"))
(define 418-IM-A-TEAPOT         (ws-status 418 "I'm a teapot"))
(define 426-UPGRADE-REQUIRED    (ws-status 426 "Upgrade Required"))
(define 428-PRECOND-REQUIRED    (ws-status 428 "Precondition Required"))
(define 429-TOO-MANY-REQUESTS   (ws-status 429 "Too Many Requests"))
(define 431-HEADERS-TOO-LARGE   (ws-status 431 "Request Header Fields Too Large"))
(define 451-LEGAL-UNAVAILABLE   (ws-status 451 "Unavailable For Legal Reasons"))
(define 500-INTERNAL-ERROR      (ws-status 500 "Internal Server Error"))
(define 501-NOT-IMPLEMENTED     (ws-status 501 "Not Implemented"))
(define 503-UNAVAILABLE         (ws-status 503 "Unavailable"))
(define 503-NOT-EXTENDED        (ws-status 510 "Not Extended"))
(define 511-NET-AUTH-REQUIRED   (ws-status 511 "Network Authentication Required"))

(module+ test (require rackunit))

(define (valid-response-status? s)
  (and (ws-status? s)
       (>= 599 (ws-status-code s) 100)))

(module+ test
  (check-true (valid-response-status? 200-OK))
  (check-true (valid-response-status? 400-BAD-REQUEST))
  (check-true (valid-response-status? (ws-status 111 "Make a Wish")))
  (check-false (valid-response-status? (ws-status 1 "Make a Wish")))
  (check-false (valid-response-status? 200)))